# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/florian/projects/tailor-green-vortex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/florian/projects/tailor-green-vortex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/florian/projects/tailor-green-vortex/CMakeFiles /home/florian/projects/tailor-green-vortex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/florian/projects/tailor-green-vortex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main.dir/build.make src/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named main_debug

# Build rule for target.
main_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_debug
.PHONY : main_debug

# fast build rule for target.
main_debug/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main_debug.dir/build.make src/CMakeFiles/main_debug.dir/build
.PHONY : main_debug/fast

#=============================================================================
# Target rules for targets named test_advection

# Build rule for target.
test_advection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_advection
.PHONY : test_advection

# fast build rule for target.
test_advection/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_advection.dir/build.make tests/CMakeFiles/test_advection.dir/build
.PHONY : test_advection/fast

#=============================================================================
# Target rules for targets named test_advection_debug

# Build rule for target.
test_advection_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_advection_debug
.PHONY : test_advection_debug

# fast build rule for target.
test_advection_debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_advection_debug.dir/build.make tests/CMakeFiles/test_advection_debug.dir/build
.PHONY : test_advection_debug/fast

#=============================================================================
# Target rules for targets named test_diffusion

# Build rule for target.
test_diffusion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_diffusion
.PHONY : test_diffusion

# fast build rule for target.
test_diffusion/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_diffusion.dir/build.make tests/CMakeFiles/test_diffusion.dir/build
.PHONY : test_diffusion/fast

#=============================================================================
# Target rules for targets named test_diffusion_debug

# Build rule for target.
test_diffusion_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_diffusion_debug
.PHONY : test_diffusion_debug

# fast build rule for target.
test_diffusion_debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_diffusion_debug.dir/build.make tests/CMakeFiles/test_diffusion_debug.dir/build
.PHONY : test_diffusion_debug/fast

#=============================================================================
# Target rules for targets named test_pressure_correction

# Build rule for target.
test_pressure_correction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_pressure_correction
.PHONY : test_pressure_correction

# fast build rule for target.
test_pressure_correction/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_pressure_correction.dir/build.make tests/CMakeFiles/test_pressure_correction.dir/build
.PHONY : test_pressure_correction/fast

#=============================================================================
# Target rules for targets named test_pressure_correction_debug

# Build rule for target.
test_pressure_correction_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_pressure_correction_debug
.PHONY : test_pressure_correction_debug

# fast build rule for target.
test_pressure_correction_debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_pressure_correction_debug.dir/build.make tests/CMakeFiles/test_pressure_correction_debug.dir/build
.PHONY : test_pressure_correction_debug/fast

#=============================================================================
# Target rules for targets named test_solve

# Build rule for target.
test_solve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_solve
.PHONY : test_solve

# fast build rule for target.
test_solve/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_solve.dir/build.make tests/CMakeFiles/test_solve.dir/build
.PHONY : test_solve/fast

#=============================================================================
# Target rules for targets named test_solve_debug

# Build rule for target.
test_solve_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_solve_debug
.PHONY : test_solve_debug

# fast build rule for target.
test_solve_debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_solve_debug.dir/build.make tests/CMakeFiles/test_solve_debug.dir/build
.PHONY : test_solve_debug/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_utils.dir/build.make tests/CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named test_utils_debug

# Build rule for target.
test_utils_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils_debug
.PHONY : test_utils_debug

# fast build rule for target.
test_utils_debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_utils_debug.dir/build.make tests/CMakeFiles/test_utils_debug.dir/build
.PHONY : test_utils_debug/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main_debug"
	@echo "... test_advection"
	@echo "... test_advection_debug"
	@echo "... test_diffusion"
	@echo "... test_diffusion_debug"
	@echo "... test_pressure_correction"
	@echo "... test_pressure_correction_debug"
	@echo "... test_solve"
	@echo "... test_solve_debug"
	@echo "... test_utils"
	@echo "... test_utils_debug"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

